FROM node:lts-alpine3.16 as build
RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN npm install --force
RUN npm run build

FROM node:lts-alpine3.16 as app

WORKDIR /app

COPY package*.json ./

COPY . .
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist/ ./dist/

RUN apk add --no-cache curl

EXPOSE 3000

CMD node -r '@aspecto/opentelemetry/auto-instrument' dist/main
