FROM node:lts-alpine3.16 as build

# RUN apk add --no-cache openssh-client git && mkdir -p /root/.ssh
# #RUN npm i @aspecto/opentelemetry
# COPY ssh_key /root/.ssh/id_ed25519
# RUN chmod 400 /root/.ssh/id_ed25519
RUN mkdir -p /app

WORKDIR /app

COPY . .
#ARG NPM_TOKEN_ARG 
#ENV NPM_TOKEN $NPM_TOKEN_ARG
#RUN npm config set @homingos:registry https://npm.pkg.github.com/
#RUN npm config set //npm.pkg.github.com/:_authToken ${NPM_TOKEN}
RUN npm install --force
RUN npm run build

FROM node:lts-alpine3.16 as app

WORKDIR /app

COPY package*.json ./

COPY . .
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist/ ./dist/

RUN apk add --no-cache curl

EXPOSE 3000

CMD node -r '@aspecto/opentelemetry/auto-instrument' dist/main
