SUCCESS_STATUS_CODE = 'Success'
ERROR_STATUS_CODE = 'Failed'
NOT_FOUND_STATUS_CODE = 'NotFound'
BAD_REQUEST_STATUS_CODE = 'BadRequest'


module.exports = {
  SUCCESS_STATUS_CODE,
  ERROR_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE
}